### PR TITLE
Additional logging for ssdp

### PR DESCRIPTION
**Pull request by arrmo**
A couple updates to help with ssdp debug.

### CODE REVIEW

**Comment by arrmo** [comment]
@deathbybandaid This one OK with you? Only because then I can get firmly back on main 😆. Thanks!

**Comment by deathbybandaid** [comment]
I'm on mobile, did you see the code review?

**Comment by arrmo** [comment]
Nope - but that may be me ... LOL!

**Comment by arrmo** [comment]
Will close, given all the logging updates - but it may be nice to have the "debug" format for ssdp (loglevel).

Thanks!

**Pull request closed without merging**
